DECLARE EXTERNAL FUNCTION udf_isnull
CSTRING(256) CHARACTER SET NONE, CSTRING(256) CHARACTER SET NONE
RETURNS CSTRING(256) CHARACTER SET NONE FREE_IT
ENTRY_POINT 'udf_isnull' MODULE_NAME 'My_fun.dll';
;