drop table htgl;
;
CREATE TABLE HTGL (
    HT_ID    INTEGER NOT NULL,
    HT_CODE  VARCHAR(50),
    PPMC     VARCHAR(50),
    HT_NAME  VARCHAR(100),
    HTLB     VARCHAR(20),
    HTXZ     VARCHAR(20),
    QYJF     VARCHAR(60),
    QYYF     VARCHAR(60),
    HT_QSRQ  DATE,
    HT_SXRQ  DATE,
    HT_JSRQ  DATE,
    HTZYDZ   VARCHAR(100),
    HT_HZTZ  VARCHAR(200),
    HT_JBR   VARCHAR(10),
    HT_CFDD  VARCHAR(50)
);
;
ALTER TABLE HTGL ADD CONSTRAINT PK_HTGL PRIMARY KEY (HT_ID);
;
