INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (52, 8051, '2001-11-30', '2001-12-30', '南宁市医学美容中心', '初级美容师', '', '');
INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (53, 8052, '1997-07-30', '2002-12-30', '广西中医学院', '医疗美容', '大专', '');
INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (56, 8055, '1997-12-30', '2000-12-30', '南宁职业技术学院', '服装设计与工艺', '大专', '');
INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (57, 8056, '2006-09-30', '2009-07-30', '广西民族师范学院', '新闻采编与制作', '大专', '');
INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (58, 8057, '2002-09-30', '2010-07-30', '桂林航天工业高等专科学校', '广告设计与制作', '大专', '');
INSERT INTO RYXX_JYJL (JYJL_ID, RY_NO, JY_KSRQ, JY_JSRQ, JY_ADDRESS, JY_ZYMC, JY_XLMC, JY_BZ)
               VALUES (59, 8058, '2009-12-30', '2009-12-30', '南宁职业技术学院', '室内设计', '大专', '');

COMMIT WORK;
