DECLARE EXTERNAL FUNCTION ENC_SIMON
CSTRING(256) CHARACTER SET NONE, CSTRING(256) CHARACTER SET NONE
RETURNS CSTRING(256) CHARACTER SET NONE FREE_IT
ENTRY_POINT 'ENC_SIMON' MODULE_NAME 'ENCC.dll';
DECLARE EXTERNAL FUNCTION DEC_SIMON
CSTRING(256) CHARACTER SET NONE, CSTRING(256) CHARACTER SET NONE
RETURNS CSTRING(256) CHARACTER SET NONE FREE_IT
ENTRY_POINT 'DEC_SIMON' MODULE_NAME 'ENCC.dll';